imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MobilBundle/Resources/config/services.yml" }
    - { resource: "@BaseBundle/Resources/config/services.yml" }
    - { resource: "@ProductoBundle/Resources/config/services.yml" }
    - { resource: "@AgenciaBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: tuciudad_defecto
        connections:
            # global
            tuciudad_defecto:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_defecto%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            tuciudad_agencia:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_agencia%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            tuciudad_persona:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_persona%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            tuciudad_producto:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_producto%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            tuciudad_cliente:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_cliente%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            tuciudad_organizacion:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_organizacion%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: tuciudad_organizacion
        entity_managers:
            tuciudad_defecto:
                connection: tuciudad_defecto
                mappings:
                    BaseBundle: ~
            tuciudad_agencia:
                connection: tuciudad_agencia
                mappings:
                    BaseBundle: ~
            tuciudad_persona:
                connection: tuciudad_persona
                mappings:
                    BaseBundle: ~
            tuciudad_producto:
                connection: tuciudad_producto
                mappings:
                    BaseBundle: ~
            tuciudad_cliente:
                connection: tuciudad_cliente
                mappings:
                    BaseBundle: ~
            tuciudad_organizacion:
                connection: tuciudad_organizacion
                mappings:
                    BaseBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
